/** Canonical Simplified Chinese names for every GHSL country in the asset. */
export const ISOLATION_COUNTRY_NAMES: Readonly<Record<string, string>> = {
  Afghanistan: '阿富汗',
  Algeria: '阿尔及利亚',
  Angola: '安哥拉',
  Argentina: '阿根廷',
  Armenia: '亚美尼亚',
  Australia: '澳大利亚',
  Austria: '奥地利',
  Azerbaijan: '阿塞拜疆',
  Bahrain: '巴林',
  Bangladesh: '孟加拉国',
  Belarus: '白俄罗斯',
  Belgium: '比利时',
  Benin: '贝宁',
  Bolivia: '玻利维亚',
  Brazil: '巴西',
  Bulgaria: '保加利亚',
  'Burkina Faso': '布基纳法索',
  Burundi: '布隆迪',
  Cambodia: '柬埔寨',
  Cameroon: '喀麦隆',
  Canada: '加拿大',
  'Central African Republic': '中非共和国',
  Chad: '乍得',
  Chile: '智利',
  China: '中国',
  Colombia: '哥伦比亚',
  'Costa Rica': '哥斯达黎加',
  Cuba: '古巴',
  Czechia: '捷克',
  "Côte d'Ivoire": '科特迪瓦',
  'Democratic Republic of the Congo': '刚果民主共和国',
  Denmark: '丹麦',
  Djibouti: '吉布提',
  'Dominican Republic': '多米尼加共和国',
  Ecuador: '厄瓜多尔',
  Egypt: '埃及',
  'El Salvador': '萨尔瓦多',
  'Equatorial Guinea': '赤道几内亚',
  Estonia: '爱沙尼亚',
  Ethiopia: '埃塞俄比亚',
  Finland: '芬兰',
  France: '法国',
  Gambia: '冈比亚',
  Georgia: '格鲁吉亚',
  Germany: '德国',
  Ghana: '加纳',
  Greece: '希腊',
  Guatemala: '危地马拉',
  Guinea: '几内亚',
  Haiti: '海地',
  Honduras: '洪都拉斯',
  Hungary: '匈牙利',
  India: '印度',
  Indonesia: '印度尼西亚',
  Iran: '伊朗',
  Iraq: '伊拉克',
  Ireland: '爱尔兰',
  Israel: '以色列',
  Italy: '意大利',
  Japan: '日本',
  Jordan: '约旦',
  Kazakhstan: '哈萨克斯坦',
  Kenya: '肯尼亚',
  Kuwait: '科威特',
  Kyrgyzstan: '吉尔吉斯斯坦',
  Lebanon: '黎巴嫩',
  Liberia: '利比里亚',
  Libya: '利比亚',
  Lithuania: '立陶宛',
  Madagascar: '马达加斯加',
  Malawi: '马拉维',
  Malaysia: '马来西亚',
  Mali: '马里',
  Mauritania: '毛里塔尼亚',
  Mongolia: '蒙古',
  Morocco: '摩洛哥',
  Mozambique: '莫桑比克',
  Myanmar: '缅甸',
  México: '墨西哥',
  Nepal: '尼泊尔',
  Netherlands: '荷兰',
  'New Zealand': '新西兰',
  Nicaragua: '尼加拉瓜',
  Niger: '尼日尔',
  Nigeria: '尼日利亚',
  'North Korea': '朝鲜',
  'North Macedonia': '北马其顿',
  Oman: '阿曼',
  Pakistan: '巴基斯坦',
  Palestine: '巴勒斯坦',
  Panama: '巴拿马',
  Paraguay: '巴拉圭',
  Peru: '秘鲁',
  Philippines: '菲律宾',
  Poland: '波兰',
  Portugal: '葡萄牙',
  Qatar: '卡塔尔',
  'Republic of the Congo': '刚果共和国',
  Romania: '罗马尼亚',
  Russia: '俄罗斯',
  Rwanda: '卢旺达',
  'Saudi Arabia': '沙特阿拉伯',
  Senegal: '塞内加尔',
  Serbia: '塞尔维亚',
  'Sierra Leone': '塞拉利昂',
  Singapore: '新加坡',
  Slovakia: '斯洛伐克',
  Somalia: '索马里',
  'South Africa': '南非',
  'South Korea': '韩国',
  Spain: '西班牙',
  'Sri Lanka': '斯里兰卡',
  Sudan: '苏丹',
  Sweden: '瑞典',
  Switzerland: '瑞士',
  Syria: '叙利亚',
  Taiwan: '台湾',
  Tajikistan: '塔吉克斯坦',
  Tanzania: '坦桑尼亚',
  Thailand: '泰国',
  Togo: '多哥',
  Tunisia: '突尼斯',
  Turkey: '土耳其',
  Turkmenistan: '土库曼斯坦',
  Uganda: '乌干达',
  Ukraine: '乌克兰',
  'United Arab Emirates': '阿拉伯联合酋长国',
  'United Kingdom': '英国',
  'United States': '美国',
  Uruguay: '乌拉圭',
  Uzbekistan: '乌兹别克斯坦',
  Venezuela: '委内瑞拉',
  Vietnam: '越南',
  Yemen: '也门',
  Zambia: '赞比亚',
  Zimbabwe: '津巴布韦',
};
