/**
 * Mundus's reviewed name forms for the surname snapshot.
 *
 * The community snapshot records most surnames only in Latin letters and
 * carries almost no Chinese forms. This table supplies, per record:
 *
 * - `zh`: a Chinese rendering following Xinhua transliteration practice
 *   (established forms such as 史密斯, 霍查 and 阿勒萨尼 are kept);
 * - `local`/`script`: the spelling in the country's own script where its
 *   principal language is not written in Latin letters (Батболд, Мельник,
 *   แซ่ตั้ง, ...);
 * - `latin`: a corrected Latin form where the snapshot is plainly wrong.
 *
 * Keys are `countryId|first romanized form` (or the first local form when the
 * record has no romanized form). The source snapshot itself is not modified;
 * these are editorial forms applied when the dataset is decoded.
 */
export interface SurnameNameForms {
  zh: string;
  local?: string;
  script?: string;
  latin?: string;
}

export const SURNAME_NAME_FORMS: Readonly<Record<string, SurnameNameForms>> = {
  'ne-004|Ahmadi': { zh: '艾哈迈迪', local: 'احمدی', script: 'Arabic' },
  'ne-008|Hoxha': { zh: '霍查' },
  'ne-008|Prifti': { zh: '普里夫蒂' },
  'ne-008|Shehu': { zh: '谢胡' },
  'ne-008|Dervishi': { zh: '德尔维什' },
  'ne-008|Bektashi': { zh: '贝克塔希' },
  'ne-008|Begu': { zh: '贝古' },
  'ne-008|Gjoni': { zh: '乔尼' },
  'ne-008|Leka': { zh: '莱卡' },
  'ne-008|Murati': { zh: '穆拉蒂' },
  'ne-008|Mehmeti': { zh: '梅赫梅蒂' },
  'ne-008|Hysi': { zh: '许西' },
  'ne-008|Gjika': { zh: '吉卡' },
  'ne-008|Marku': { zh: '马尔库' },
  'ne-008|Kola': { zh: '科拉' },
  'ne-008|Hasani': { zh: '哈萨尼' },
  'ne-008|Kristi': { zh: '克里斯蒂' },
  'ne-008|Luka': { zh: '卢卡' },
  'ne-008|Brahimi': { zh: '布拉希米' },
  'ne-008|Sinani': { zh: '西纳尼' },
  'ne-008|Thanasi': { zh: '塔纳西' },
  'ne-008|Halili': { zh: '哈利利' },
  'ne-008|Abazi': { zh: '阿巴齐' },
  'ne-008|Dibra': { zh: '迪布拉' },
  'ne-008|Laçi': { zh: '拉奇' },
  'ne-008|Shkodra': { zh: '什科德拉' },
  'ne-008|Prishtina': { zh: '普里什蒂纳' },
  'ne-008|Delvina': { zh: '德尔维纳' },
  'ne-008|Koroveshi': { zh: '科罗韦希' },
  'ne-008|Përmeti': { zh: '佩尔梅蒂' },
  'ne-008|Frashëri': { zh: '弗拉舍里' },
  'ne-008|Gega': { zh: '盖加' },
  'ne-008|Toska': { zh: '托斯卡' },
  'ne-008|Çami': { zh: '查米' },
  'ne-008|Kelmendi': { zh: '凯尔门迪' },
  'ne-008|Shkreli': { zh: '什克雷利' },
  'ne-008|Berisha': { zh: '贝里沙' },
  'ne-008|Krasniqi': { zh: '克拉斯尼奇' },
  'ne-008|Gashi': { zh: '加希' },
  'ne-008|Kuqi': { zh: '库奇' },
  'ne-008|Bardhi': { zh: '巴尔迪' },
  'ne-012|Saidi': { zh: '赛义迪', local: 'سعيدي', script: 'Arabic' },
  'ne-020|Mora': { zh: '莫拉' },
  'ne-024|Manuel': { zh: '曼努埃尔' },
  'ne-028|James': { zh: '詹姆斯' },
  'ne-031|Mammadov': { zh: '马梅多夫' },
  'ne-032|González': { zh: '冈萨雷斯' },
  'ne-036|Smith': { zh: '史密斯' },
  'ne-040|Gruber': { zh: '格鲁伯' },
  'ne-044|Rolle': { zh: '罗尔' },
  'ne-048|Al-Doseri': { zh: '多塞里', local: 'الدوسري', script: 'Arabic' },
  'ne-050|Akter': { zh: '阿克特尔' },
  'ne-051|Grigoryan': { zh: '格里戈良' },
  'ne-052|Clarke': { zh: '克拉克' },
  'ne-056|Peeters': { zh: '佩特斯' },
  'ne-064|Wangchuk': { zh: '旺楚克', local: 'དབང་ཕྱུག', script: 'Tibetan' },
  'ne-068|Mamani': { zh: '马马尼' },
  'ne-070|Hodžić': { zh: '霍季奇' },
  'ne-070|Hadžić': { zh: '哈季奇' },
  'ne-070|Čengić': { zh: '琴吉奇' },
  'ne-070|Delić': { zh: '德利奇' },
  'ne-070|Demirović': { zh: '德米罗维奇' },
  'ne-070|Kovačević': { zh: '科瓦切维奇' },
  'ne-070|Tahirović': { zh: '塔希罗维奇' },
  'ne-070|Ferhatović': { zh: '费尔哈托维奇' },
  'ne-070|Muratović': { zh: '穆拉托维奇' },
  'ne-070|Ibrahimović': { zh: '伊布拉希莫维奇' },
  'ne-070|Hasanović': { zh: '哈萨诺维奇' },
  'ne-070|Mehmedović': { zh: '梅赫梅多维奇' },
  'ne-070|Salihović': { zh: '萨利霍维奇' },
  'ne-070|Terzić': { zh: '泰尔齐奇' },
  'ne-070|Ademović': { zh: '阿德莫维奇' },
  'ne-070|Adilović': { zh: '阿迪洛维奇' },
  'ne-070|Delemović': { zh: '德莱莫维奇' },
  'ne-070|Zukić': { zh: '祖基奇' },
  'ne-070|Krličević': { zh: '克尔利切维奇' },
  'ne-070|Suljić': { zh: '苏利奇' },
  'ne-070|Ahmetović': { zh: '艾哈迈托维奇' },
  'ne-070|Subotić': { zh: '苏博蒂奇' },
  'ne-070|Savić': { zh: '萨维奇' },
  'ne-070|Popović': { zh: '波波维奇' },
  'ne-070|Jovanović': { zh: '约万诺维奇' },
  'ne-070|Petrović': { zh: '彼得罗维奇' },
  'ne-070|Đurić': { zh: '久里奇' },
  'ne-070|Babić': { zh: '巴比奇' },
  'ne-070|Lukić': { zh: '卢基奇' },
  'ne-070|Knežević': { zh: '克内泽维奇' },
  'ne-070|Marković': { zh: '马尔科维奇' },
  'ne-070|Ilić': { zh: '伊利奇' },
  'ne-070|Đukić': { zh: '久基奇' },
  'ne-070|Vuković': { zh: '武科维奇' },
  'ne-070|Vujić': { zh: '武伊奇' },
  'ne-070|Simić': { zh: '西米奇' },
  'ne-070|Radić': { zh: '拉迪奇' },
  'ne-070|Nikolić': { zh: '尼科利奇' },
  'ne-070|Marić': { zh: '马里奇' },
  'ne-070|Mitrović': { zh: '米特罗维奇' },
  'ne-070|Tomić': { zh: '托米奇' },
  'ne-070|Božić': { zh: '博日奇' },
  'ne-070|Golubović': { zh: '戈卢博维奇' },
  'ne-070|Mirković': { zh: '米尔科维奇' },
  'ne-072|Molefe': { zh: '莫勒费' },
  'ne-076|Silva': { zh: '席尔瓦' },
  'ne-084|Martinez': { zh: '马丁内斯' },
  "ne-090|Ma'ae": { zh: '马阿埃' },
  'ne-096|Haji': { zh: '哈吉' },
  'ne-100|Ivanov': { zh: '伊万诺夫' },
  'ne-104|Aung': { zh: '昂', local: 'အောင်', script: 'Myanmar' },
  'ne-108|Nkurunziza': { zh: '恩库伦齐扎' },
  // Belarusian rather than the Russian variant listed first by the source.
  'ne-112|Ivanoŭ': { zh: '伊万诺夫', local: 'Іваноў', script: 'Cyrillic' },
  'ne-116|កូយ': { zh: '科伊', latin: 'Koy' },
  'ne-120|Ngo': { zh: '恩戈' },
  'ne-124|Smith': { zh: '史密斯' },
  'ne-132|Lopes': { zh: '洛佩斯' },
  'ne-140|Yaloke': { zh: '亚洛凯' },
  'ne-144|Perera': { zh: '佩雷拉', local: 'පෙරේරා', script: 'Sinhala' },
  'ne-148|Mahamat': { zh: '马哈马特', local: 'محمد', script: 'Arabic' },
  'ne-152|González': { zh: '冈萨雷斯' },
  'ne-156|Wáng': { zh: '王' },
  'ne-158|Chén': { zh: '陈' },
  'ne-170|Rodríguez': { zh: '罗德里格斯' },
  'ne-174|Muhammad': { zh: '穆罕默德', local: 'محمد', script: 'Arabic' },
  'ne-178|Ngoma': { zh: '恩戈马' },
  'ne-180|Ilunga': { zh: '伊伦加' },
  'ne-188|Hernández': { zh: '埃尔南德斯' },
  'ne-191|Horvat': { zh: '霍尔瓦特' },
  'ne-192|Rodríguez': { zh: '罗德里格斯' },
  'ne-196|Georgiou': { zh: '耶奥尔尤', local: 'Γεωργίου', script: 'Greek' },
  'ne-203|Novák': { zh: '诺瓦克' },
  'ne-204|Bio': { zh: '比奥' },
  'ne-208|Nielsen': { zh: '尼尔森' },
  'ne-212|Laurent': { zh: '洛朗' },
  'ne-214|Rodríguez': { zh: '罗德里格斯' },
  'ne-218|Quishpe': { zh: '基什佩' },
  // The source row lists the Swedish "Andersson" first for El Salvador; the
  // record's own second form, Hernández, is the Salvadoran surname.
  'ne-222|Andersson': {
    zh: '埃尔南德斯',
    local: 'Hernández',
    script: 'Latin',
    latin: 'Hernández',
  },
  'ne-226|Nguema': { zh: '恩圭马' },
  'ne-231|Tesfaye': { zh: '特斯法耶', local: 'ተስፋዬ', script: 'Ethiopic' },
  'ne-232|Ali': { zh: '阿里', local: 'ዓሊ', script: 'Ethiopic' },
  'ne-233|Ivanov': { zh: '伊万诺夫' },
  'ne-234|Joensen': { zh: '约恩森' },
  'ne-242|Kumar': { zh: '库马尔' },
  'ne-246|Korhonen': { zh: '科尔霍宁' },
  'ne-250|Martin': { zh: '马丁' },
  'ne-262|Muhamed': { zh: '穆罕默德', local: 'محمد', script: 'Arabic' },
  'ne-266|Ndong': { zh: '恩东' },
  'ne-268|Beridze': { zh: '贝里泽' },
  'ne-270|Jallow': { zh: '贾洛' },
  'ne-275|Hamad': { zh: '哈马德', local: 'حمد', script: 'Arabic' },
  'ne-276|Müller': { zh: '穆勒' },
  'ne-288|Mensah': { zh: '门萨' },
  'ne-296|Tekaai': { zh: '特卡伊' },
  'ne-300|Samaras': { zh: '萨马拉斯' },
  'ne-300|Papoutsis': { zh: '帕普齐斯' },
  'ne-300|Kritikos': { zh: '克里蒂科斯' },
  'ne-300|Aivaliotis': { zh: '艾瓦利奥蒂斯' },
  'ne-300|Kontos': { zh: '孔多斯' },
  'ne-300|Mytaras': { zh: '米塔拉斯' },
  'ne-300|Koufos': { zh: '库福斯' },
  'ne-308|Williams': { zh: '威廉斯' },
  'ne-320|López': { zh: '洛佩斯' },
  'ne-324|Diallo': { zh: '迪亚洛' },
  'ne-328|Persaud': { zh: '珀索德' },
  'ne-332|Jean': { zh: '让' },
  'ne-336|Benedetti': { zh: '贝内代蒂' },
  'ne-340|Hernandez': { zh: '埃尔南德斯' },
  'ne-348|Nagy': { zh: '纳吉' },
  'ne-352|Blöndal': { zh: '布伦达尔' },
  'ne-356|Devi': { zh: '德维' },
  'ne-360|Setiawan': { zh: '塞蒂亚万' },
  'ne-364|Mohammadi': { zh: '穆罕默迪' },
  'ne-368|Ali': { zh: '阿里', local: 'علي', script: 'Arabic' },
  'ne-372|Murphy': { zh: '墨菲' },
  'ne-376|Cohen': { zh: '科恩' },
  'ne-380|Rossi': { zh: '罗西' },
  'ne-384|Kone': { zh: '科内' },
  'ne-388|Brown': { zh: '布朗' },
  'ne-392|Satō': { zh: '佐藤' },
  'ne-398|Ahmetov': { zh: '艾哈迈托夫' },
  'ne-400|Al-Majali': { zh: '马贾利', local: 'المجالي', script: 'Arabic' },
  'ne-404|Mwangi': { zh: '姆旺吉' },
  'ne-408|Kim': { zh: '金', local: '김', script: 'Hangul' },
  'ne-410|Kim': { zh: '金', local: '김', script: 'Hangul' },
  'ne-414|Al-Sabah': { zh: '萨巴赫', local: 'الصباح', script: 'Arabic' },
  'ne-417|Sadykov': { zh: '萨德科夫', local: 'Садыков', script: 'Cyrillic' },
  'ne-418|Phommasone': { zh: '蓬马颂', local: 'ພົມມະສອນ', script: 'Lao' },
  'ne-422|Haddad': { zh: '哈达德', local: 'حداد', script: 'Arabic' },
  'ne-426|Mohapi': { zh: '莫哈皮' },
  'ne-428|Bērziņš': { zh: '贝尔津什' },
  'ne-430|Kollie': { zh: '科利' },
  'ne-434|Ali': { zh: '阿里', local: 'علي', script: 'Arabic' },
  'ne-438|Frick': { zh: '弗里克' },
  'ne-440|Kazlauskas': { zh: '卡兹劳斯卡斯' },
  'ne-442|Schmit': { zh: '施密特' },
  'ne-450|Rakotomalala': { zh: '拉科托马拉拉' },
  'ne-454|Banda': { zh: '班达' },
  'ne-458|Ismail': { zh: '伊斯梅尔' },
  'ne-462|Ahmed': { zh: '艾哈迈德', local: 'އަޙްމަދު', script: 'Thaana' },
  'ne-466|Traore': { zh: '特拉奥雷' },
  'ne-470|Borg': { zh: '博格' },
  'ne-478|Ould': { zh: '乌尔德', local: 'ولد', script: 'Arabic' },
  'ne-480|Beeharry': { zh: '比哈里' },
  'ne-484|Hernández': { zh: '埃尔南德斯' },
  'ne-492|Grimaldi': { zh: '格里马尔迪' },
  'ne-496|Batbold': { zh: '巴特包勒德', local: 'Батболд', script: 'Cyrillic' },
  'ne-498|Rusu': { zh: '鲁苏' },
  'ne-499|Popović': { zh: '波波维奇' },
  'ne-504|Alaoui': { zh: '阿拉维', local: 'العلوي', script: 'Arabic' },
  'ne-508|Langa': { zh: '兰加' },
  'ne-512|Al-Harthy': { zh: '哈尔西', local: 'الحارثي', script: 'Arabic' },
  'ne-516|Johannes': { zh: '约翰内斯' },
  'ne-520|Jeremiah': { zh: '耶利米' },
  'ne-524|Chaudhary': { zh: '乔杜里' },
  'ne-528|De Jong': { zh: '德容' },
  'ne-548|Bule': { zh: '布莱' },
  'ne-554|Singh': { zh: '辛格' },
  'ne-558|Lopez': { zh: '洛佩斯' },
  'ne-562|Abdou': { zh: '阿卜杜' },
  'ne-566|Ibrahim': { zh: '易卜拉欣' },
  'ne-578|Hansen': { zh: '汉森' },
  'ne-583|Palik': { zh: '帕利克' },
  'ne-584|Kabua': { zh: '卡布亚' },
  'ne-585|Uduch': { zh: '乌杜赫' },
  'ne-586|Khan': { zh: '汗', local: 'خان', script: 'Arabic' },
  'ne-591|Gonzalez': { zh: '冈萨雷斯' },
  'ne-598|Kua': { zh: '夸' },
  'ne-600|González': { zh: '冈萨雷斯' },
  'ne-604|Quispe': { zh: '基斯佩' },
  'ne-608|dela Cruz': { zh: '德拉克鲁斯' },
  'ne-616|Nowak': { zh: '诺瓦克' },
  'ne-620|Silva': { zh: '席尔瓦' },
  'ne-624|Gomes': { zh: '戈梅斯' },
  'ne-626|da Costa': { zh: '达科斯塔' },
  'ne-634|Al-Thani': { zh: '阿勒萨尼', local: 'آل ثاني', script: 'Arabic' },
  'ne-642|Popa': { zh: '波帕' },
  // Without the stress mark the source copied from a dictionary entry.
  'ne-643|Smirnov': { zh: '斯米尔诺夫', local: 'Смирнов', script: 'Cyrillic' },
  'ne-646|Uwimana': { zh: '乌维马纳' },
  'ne-659|Liburd': { zh: '利伯德' },
  'ne-662|Charles': { zh: '查尔斯' },
  'ne-670|King': { zh: '金' },
  'ne-674|Gasperoni': { zh: '加斯佩罗尼' },
  'ne-678|do Sacramento': { zh: '杜萨克拉门托' },
  'ne-682|Al-Ghamdi': { zh: '加姆迪', local: 'الغامدي', script: 'Arabic' },
  'ne-686|Ndiaye': { zh: '恩迪亚耶' },
  'ne-688|Jovanović': { zh: '约万诺维奇' },
  'ne-690|Hoareau': { zh: '奥罗' },
  'ne-694|Kamare': { zh: '卡马雷' },
  // "Tan" is the Hokkien romanization of 陈.
  'ne-702|Tan': { zh: '陈', local: '陈', script: 'Han' },
  'ne-703|Horváth': { zh: '霍尔瓦特' },
  // Vietnamese is written in Latin letters (chữ Quốc ngữ); 阮 is its Han form.
  'ne-704|Nguyễn': { zh: '阮', local: 'Nguyễn', script: 'Latin' },
  'ne-705|Novak': { zh: '诺瓦克' },
  'ne-706|Ali': { zh: '阿里' },
  'ne-710|Nkosi': { zh: '恩科西' },
  'ne-716|Moyo': { zh: '莫约' },
  'ne-724|García': { zh: '加西亚' },
  'ne-728|Deng': { zh: '邓' },
  'ne-729|Ahmed': { zh: '艾哈迈德', local: 'أحمد', script: 'Arabic' },
  'ne-740|Lin': { zh: '林' },
  'ne-748|Dlamini': { zh: '德拉米尼' },
  'ne-752|Andersson': { zh: '安德松' },
  'ne-756|Müller': { zh: '穆勒' },
  'ne-760|Ahmad': { zh: '艾哈迈德', local: 'أحمد', script: 'Arabic' },
  'ne-762|Sharipov': { zh: '沙里波夫', local: 'Шарипов', script: 'Cyrillic' },
  // แซ่ตั้ง (sae + Teochew "tang") is the Thai rendering of the surname 陈.
  'ne-764|Saetang': { zh: '陈', local: 'แซ่ตั้ง', script: 'Thai' },
  'ne-768|Lawson': { zh: '劳森' },
  'ne-776|Havea': { zh: '哈维亚' },
  'ne-780|Mohammed': { zh: '穆罕默德' },
  'ne-784|Al-Mansoori': { zh: '曼苏里', local: 'المنصوري', script: 'Arabic' },
  'ne-788|Trabelsi': { zh: '特拉贝尔西', local: 'الطرابلسي', script: 'Arabic' },
  'ne-792|Yılmaz': { zh: '耶尔马兹' },
  'ne-795|Berdimuradov': { zh: '别尔德穆拉多夫' },
  'ne-798|Talake': { zh: '塔拉凯' },
  'ne-800|Akello': { zh: '阿凯洛' },
  'ne-804|Melnyk': { zh: '梅尔尼克', local: 'Мельник', script: 'Cyrillic' },
  'ne-807|Andov': { zh: '安多夫', local: 'Андов', script: 'Cyrillic' },
  'ne-818|Mohamed': { zh: '穆罕默德', local: 'محمد', script: 'Arabic' },
  'ne-826|Brown': { zh: '布朗' },
  'ne-834|Juma': { zh: '朱马' },
  'ne-840|Smith': { zh: '史密斯' },
  // The source misspells Ouédraogo with a Q.
  'ne-854|Quedraogo': {
    zh: '韦德拉奥果',
    local: 'Ouédraogo',
    script: 'Latin',
    latin: 'Ouédraogo',
  },
  'ne-858|Pereira': { zh: '佩雷拉' },
  'ne-860|Tursunov': { zh: '图尔苏诺夫' },
  'ne-862|Rodriguez': { zh: '罗德里格斯' },
  'ne-882|Sefo': { zh: '塞福' },
  'ne-887|Al-Hadi': { zh: '哈迪', local: 'الهادي', script: 'Arabic' },
  'ne-894|Phiri': { zh: '菲里' },
  'ne-x-kosovo|Krasniqi': { zh: '克拉斯尼奇' },
};
